// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCZ8nJzt86yU9hgClQ-UIIvRzaM07DSq8',
    appId: '1:245376294300:web:8e4651f4181f973ad23c59',
    messagingSenderId: '245376294300',
    projectId: 'databasefutbol-8b32b',
    authDomain: 'databasefutbol-8b32b.firebaseapp.com',
    storageBucket: 'databasefutbol-8b32b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRMjmWFHYwg9LEhN9bN39tyD3ClqhlQiU',
    appId: '1:245376294300:android:ffa7f4954ccd6f60d23c59',
    messagingSenderId: '245376294300',
    projectId: 'databasefutbol-8b32b',
    storageBucket: 'databasefutbol-8b32b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7lTFCYgG4A3KHBTBOvHkiEIg0SbHFN-M',
    appId: '1:245376294300:ios:d3b0d50d67366bc5d23c59',
    messagingSenderId: '245376294300',
    projectId: 'databasefutbol-8b32b',
    storageBucket: 'databasefutbol-8b32b.firebasestorage.app',
    iosBundleId: 'com.codigocorrecto.ligaAppNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7lTFCYgG4A3KHBTBOvHkiEIg0SbHFN-M',
    appId: '1:245376294300:ios:d3b0d50d67366bc5d23c59',
    messagingSenderId: '245376294300',
    projectId: 'databasefutbol-8b32b',
    storageBucket: 'databasefutbol-8b32b.firebasestorage.app',
    iosBundleId: 'com.codigocorrecto.ligaAppNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCZ8nJzt86yU9hgClQ-UIIvRzaM07DSq8',
    appId: '1:245376294300:web:c89b60047a6a8277d23c59',
    messagingSenderId: '245376294300',
    projectId: 'databasefutbol-8b32b',
    authDomain: 'databasefutbol-8b32b.firebaseapp.com',
    storageBucket: 'databasefutbol-8b32b.firebasestorage.app',
  );
}
